In [39]:
import crispr_assembler as ca
import pandas as pd
import numpy as np

In [61]:
new_ecoli = pd.read_excel("../../article/data/answers/new_ecoli.xlsx", sheet_name=None, header = None, index_col=None)

In [62]:
new_ecoli.keys()

odict_keys(['Ecoli кассета 1', 'Ecoli кассета 2'])

In [63]:
new_ecoli_1 = new_ecoli['Ecoli кассета 1']

In [65]:
def update(answer, source , prefix):
    for i, row in source.iterrows():
        names = row[0]
        if type(names) == str:
            names = [int(x) for x in names.split(',')]
        else:
            names = [names]

        for name in names:         
            mask = pd.notna(row[1:]).values
            array = "\t".join(row[1:].values[mask])
        
            answer[prefix + str(name)] = array

In [68]:
new_ecoli_dict = {}
update(new_ecoli_dict, new_ecoli['Ecoli кассета 1'], 'first_')
update(new_ecoli_dict, new_ecoli['Ecoli кассета 2'], 'second_')

In [96]:
def save_dict(d, fname):
    with open(fname, 'w') as f:

        for k,v in d.items():
            f.write(k)
            f.write("\n")
            f.write(v)
            f.write("\n")

    

In [74]:
sensivity_set = [2,3,5,7,8,11,14,15,21,22]

In [80]:
keys  = np.array([int(x.split('_')[1]) for x in new_ecoli_dict.keys()])

for x in sensivity_set:
    if x in keys:
        print(np.where(keys == x))
    else: 
        print(x)
    

(array([ 2, 23]),)
(array([ 7, 32]),)
(array([ 8, 27]),)
(array([10, 33]),)
(array([11, 34]),)
(array([ 1, 35]),)
(array([12, 36]),)
(array([13, 37]),)
(array([18, 29]),)
(array([16, 40]),)


In [85]:
keys

array([ 1, 11,  2, 24, 61, 62, 68,  3,  5, 50,  7,  8, 14, 15, 19, 20, 22,
       31, 21, 23, 27, 65,  1,  2, 61, 62, 68,  5, 50, 21, 65, 70,  3,  7,
        8, 11, 14, 15, 19, 20, 22, 23, 24, 27, 31])

In [89]:
def filter_dict(data_dict, list_tags):
    filtered_dict = {}
    
    for k,v in data_dict.items():
        if int(k.split("_")[1]) in list_tags:
            filtered_dict[k] = v
        
    return filtered_dict

In [97]:
save_dict(filter_dict(new_ecoli_dict, sensivity_set), "../../article/data/answers/sensivity")