In [1]:
import crispr_assembler as ca
import pandas as pd
import numpy as np

In [2]:
new_ecoli = pd.read_excel("./Cheked spacers EColi.xlsx", sheet_name=None, header = None, index_col=None)

In [3]:
new_ecoli.keys()

odict_keys(['CRISPR1', 'CRISPR2'])

In [63]:
new_ecoli_1 = new_ecoli['Ecoli кассета 1']

In [4]:
def update(answer, source , prefix):
    for i, row in source.iterrows():
        names = row[0]
        if type(names) == str:
            names = [int(x) for x in names.split(',')]
        else:
            names = [names]

        for name in names:         
            mask = pd.notna(row[1:]).values
            array = "\t".join(row[1:].values[mask])
        
            answer[prefix + str(name)] = array

In [5]:
new_ecoli_dict = {}
update(new_ecoli_dict, new_ecoli['CRISPR1'], 'first_')
update(new_ecoli_dict, new_ecoli['CRISPR2'], 'second_')

In [6]:
new_ecoli_dict

{'first_2': 'TCTTACTGCTTGGTATGCGGAATCACACCCTGAA\tACTGAAGCATCAAACATTTGGTGGACCAAACGGA\tACTGTACGCGGCGAGTTTTAGCGACAGGTCATCC\tACGGATCTGCCAGCGCCTCTGCGGGGCGGTAAAC',
 'first_3': 'GTACGCGGCGAGTTTTAGCGACAGGTCATCC\tGATCTGCCAGCGCCTCTGCGGGGCGGTAAAC\tACGCCAGCCACCTGCTTCGCCAGCCGTTCGG\tCACGGTAGCGCCACTGCGCGTCGGTGACGGG\tACGAACAGGGATTTGTCGGCAGTTTCTTTAC\tTAATTCGCAAATCAATATATATTTTGTCCGT\tATTGCGGATGCTCCCGGAATTGCGCGGGCAA',
 'first_5': 'CAGCGTCAGGCGTGAAATCTCACCGTCGTTGC\tTCGGTTCAGGCGTTGCAAACCTGGCTACCGGG\tGTAGTCCATCATTCCACCTATGTCTGAACTCC\tCCGGGGGATAATGTTTACGGTCATGCGCCCCC\tATCGTCCATATTAACAATCGTGGTGAGTTCAA\tACTATGGCCCCGGCAAAAAACGCGCTGGTGGG\tTGGGCGGCTTGCCTTGCAGCCAGCTCCAGCAG\tAAGCTGGCTGGCAATCTCTTTCGGGGTGAGTC\tTAGTTTCCGTATCTCCGGATTTATAAAGCTGA\tGCAGGCGGCGACGCGCAGGGTATGCGCGATTCG\tGCGACCGCTCAGAAATTCCAGACCCGATCCAAA',
 'first_7': 'TCACGCGCTGTTACCCAGTCCCTTTTTTTCAG\tCGCCGCGGACTCACGAGCAGACCATCACAGAC\tGCAGACTATAACGAGGGTCGCACGCGGATCAT\tTACCAAACCGGAATCTTTCCATATAACGGCGG\tTTACTCGCCGGGGAATACGCCCCGCGCCACGC\tCTTACTCATTCAGAACGCTGCATG

In [7]:
def save_dict(d, fname):
    with open(fname, 'w') as f:

        for k,v in d.items():
            f.write(k)
            f.write("\n")
            f.write(v)
            f.write("\n")

    

In [8]:
sensivity_set = [2,3,5,7,8,11,14,15,21,22]

In [ ]:
3,5,14,15,8,21,

In [9]:
keys  = np.array([int(x.split('_')[1]) for x in new_ecoli_dict.keys()])

for x in sensivity_set:
    if x in keys:
        print(np.where(keys == x))
    else: 
        print(x)
    

(array([ 0, 10]),)
(array([ 1, 11]),)
(array([ 2, 12]),)
(array([ 3, 13]),)
(array([ 4, 14]),)
(array([ 5, 15]),)
(array([ 6, 16]),)
(array([ 7, 17]),)
(array([ 8, 18]),)
(array([ 9, 19]),)


In [10]:
keys

array([ 2,  3,  5,  7,  8, 11, 14, 15, 21, 22,  2,  3,  5,  7,  8, 11, 14,
       15, 21, 22])

In [11]:
def filter_dict(data_dict, list_tags):
    filtered_dict = {}
    
    for k,v in data_dict.items():
        if int(k.split("_")[1]) in list_tags:
            filtered_dict[k] = v
        
    return filtered_dict

In [12]:
save_dict(filter_dict(new_ecoli_dict, sensivity_set), "../../article/data/answers/sensivity")