In [1]:
import tensorflow as tf
import numpy as np

In [2]:
node1 = tf.constant(3.0)
node2 = tf.constant(4.0)
print(node1, node2)

Tensor("Const:0", shape=(), dtype=float32) Tensor("Const_1:0", shape=(), dtype=float32)


In [3]:
sess = tf.Session()
print(sess.run([node1,node2]))

[3.0, 4.0]


In [4]:
node3 = tf.add(node1, node2)
print(sess.run([node3]))

[7.0]


In [5]:
a = tf.placeholder(dtype=tf.float32)
b = tf.placeholder(dtype=tf.float32)
adder_node = a + b

In [6]:
print(sess.run(adder_node, {
    a : [1, 2],
    b : [3, 5]
}))

[ 4.  7.]


In [31]:
W = tf.Variable([.3])
b = tf.Variable([-.3])
x = tf.placeholder(tf.float32)
linear_model = W*x + b

In [32]:
init = tf.global_variables_initializer()
sess.run(init)

In [33]:
sess.run(linear_model, {x : [1,2,3]})

array([ 0.        ,  0.30000001,  0.60000002], dtype=float32)

In [34]:
y = tf.placeholder(tf.float32)
loss = tf.reduce_sum((linear_model - y)**2)

print(sess.run(loss, {x: [1, 2, 3, 4], y: [0, -1, -2, -3]}))

23.66


In [37]:
fixW = tf.assign(W, [-1.])
fixb = tf.assign(b, [1.])
sess.run([fixW, fixb])
print(sess.run(loss, {x: [1, 2, 3, 4], y: [0, -1, -2, -3]}))


0.0


In [38]:
sess.run(init)
sess.run([W, b])

[array([ 0.30000001], dtype=float32), array([-0.30000001], dtype=float32)]

In [47]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

In [48]:
sess.run(init)
for i in range(100):
    sess.run(train, {x : [1, 2, 3], y : [-2, -3, -4]})

In [49]:
sess.run([W, b])

[array([-1.02289987], dtype=float32), array([-0.94794321], dtype=float32)]

#### Estimator

In [67]:
cols = [tf.feature_column.numeric_column('x')]

est = tf.estimator.LinearRegressor(cols)

x_train = np.array([1,2,3])
y_train = np.array([-2.1, -3, -4.1])

x_test = np.array([3,4,6])
y_test = np.array([-4.1, -5.2, -6.1])

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmp8ls2nzsr', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fe99e5a6c18>, '_task_type': 'worker', '_task_id': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [68]:
train = tf.estimator.inputs.numpy_input_fn({'x' : x_train}, y_train, 2, 100, True)

In [69]:
train()

({'x': <tf.Tensor 'random_shuffle_queue_DequeueUpTo:1' shape=(?,) dtype=int64>},
 <tf.Tensor 'random_shuffle_queue_DequeueUpTo:2' shape=(?,) dtype=float64>)

## MNIST

#### no deep

In [2]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [75]:
x = tf.placeholder(tf.float32, [None, 784])

W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

y = tf.nn.softmax(tf.matmul(x, W) + b)

In [76]:
y_ = tf.placeholder(tf.float32, [None, 10])

In [77]:
cross_entropy = -tf.reduce_mean(tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]))

In [78]:
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

In [79]:
sess = tf.InteractiveSession()

In [81]:
tf.global_variables_initializer().run()

In [82]:
for _ in range(1000):
    batch_xs, batch_ys = mnist.train.next_batch(100)
    sess.run(train_step, feed_dict={x: batch_xs, y_: batch_ys})


In [91]:
correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))
quality = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [93]:
sess.run(quality, {x: mnist.test.images, y_ :mnist.test.labels})

0.91189998

#### deep

In [63]:
x = tf.placeholder(tf.float32, shape=[None, 784])
y_ = tf.placeholder(tf.float32, shape=[None, 10])

In [64]:
def init_var(shape):
    init = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(init)
#def bias_var(shape):
    

In [65]:
def conv2d(x, W):
    return tf.nn.conv2d(x, W, strides = [1,1,1,1], padding='SAME')

def max_pool2d(x):
    return tf.nn.max_pool(x, ksize = [1,2,2,1], strides = [1,2,2,1], padding='SAME')


In [68]:
l_resh = tf.reshape(x, [-1,28,28,1])

w_1 = init_var([5,5,1,32])
l_conv_1 = conv2d(l_resh, w_1)
l_pool_1 = max_pool2d(l_conv_1)
w_2 = init_var([5,5,32,64])
l_conv_2 = conv2d(l_pool_1, w_2)
l_pool_2 = max_pool2d(l_conv_2)

l_resh_2 = tf.reshape(l_pool_2, [-1, 7 * 7 * 64])

In [69]:
l_resh_2.get_shape().as_list()

[None, 3136]

In [70]:
W_dense_1 = init_var([7*7*64, 1000])
b_dense_1 = init_var([1000])
l_dense_1 = tf.nn.relu(tf.matmul(l_resh_2, W_dense_1) + b_dense_1)

prob = tf.placeholder(tf.float32)
l_dropout = tf.nn.dropout(l_dense_1, prob)

W_dense_2 = init_var([1000, 10])
b_dense_2 = init_var([10])
l_dense_2 = tf.matmul(l_dropout, W_dense_2) + b_dense_2

In [71]:
l_dense_2.get_shape().as_list()

[None, 10]

In [75]:
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=l_dense_2, labels=y_))
train = tf.train.AdamOptimizer().minimize(loss)

correct = tf.equal(tf.argmax(l_dense_2, 1), tf.argmax(y_, 1))
accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))

In [76]:
acc_list = []

In [78]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(200):
        batch = mnist.train.next_batch(50)
        
        if i % 100 == 0:
            acc = accuracy.eval({x : batch[0], y_ : batch[1], prob : 1})
            print(i, acc)
            acc_list.append(acc)
        
        train.run({x: batch[0], y_: batch[1], prob: 0.5})
        
    print('test accuracy %g' % accuracy.eval(feed_dict={
          x: mnist.test.images[:2000], y_: mnist.test.labels[:2000], prob: 1}))
    

0 0.08
100 0.92
test accuracy 0.9455


#### MSE check`

In [214]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)    

In [216]:
mse = tf.reduce_mean(tf.squared_difference(a, b), 1)

In [223]:
tn = tf.truncated_normal((10,10)) / 10

In [224]:
sess2 = tf.Session()
sess2.run(tf.global_variables_initializer())

sess2.run([mse, tn], {a : gamma_arr, b : gamma_arr})

[array([ 0.,  0.,  0.,  0.], dtype=float32),
 array([[-0.06959507, -0.09057277,  0.10963985,  0.08222605, -0.03869854,
         -0.06150661, -0.10598619, -0.01464909, -0.18092424, -0.17417203],
        [ 0.05788362, -0.14508286,  0.09065788,  0.1285512 , -0.05893765,
          0.16565351, -0.05170033,  0.03498211, -0.0126902 ,  0.098424  ],
        [ 0.04547034,  0.12770982, -0.00952954, -0.11951027, -0.02438813,
          0.09063514, -0.04326795,  0.14002629, -0.02527756,  0.09974826],
        [ 0.09416965, -0.0439852 , -0.02998312,  0.068509  , -0.00446869,
          0.0603765 , -0.03120703,  0.03979282, -0.05558593, -0.1134274 ],
        [ 0.14467172, -0.18102184,  0.05375842,  0.14329427,  0.11629945,
          0.06735642, -0.06428711,  0.00029542, -0.05016619,  0.06902727],
        [ 0.19268389,  0.19295511,  0.05005402,  0.01324972, -0.04859195,
         -0.09160911,  0.08356685, -0.10766944, -0.04014878, -0.17556509],
        [ 0.0850774 ,  0.08239626,  0.03554998, -0.07630973, 

## Loops

In [1]:
import tensorflow as tf
import numpy as np

In [5]:
i = tf.constant(0)
c = lambda i: tf.less(i, 10)
b = lambda i: tf.add(i, 1)
r = tf.while_loop(c, b, [i])


In [3]:
#loops = tf.constant([10])
i = tf.constant(0)
c = lambda i: tf.less(i, 10)


def b(i):
    #print("sa")
    b 
    return tf.add(i, 2)

In [7]:
N = 4
D = 2
K = 3

In [8]:
gamma_arr = np.array([[0.5, 0.1, 0.4], [0.3, .4, .3],[0.3, .4, .3],[0.1, .1, .8] ])

z_arr = np.array(([[1,2], [4,3] ,[4,3], [2, 1]]))

In [9]:
gamma = tf.placeholder(tf.float32)
z = tf.placeholder(tf.float32)    

In [208]:
def est_gmm(gamma, z):
    weights = tf.reduce_mean(gamma, reduction_indices=[0])
    means = tf.transpose(tf.matmul(tf.transpose(z), gamma) / tf.transpose(tf.reduce_sum(gamma, reduction_indices=[0])))
    
    z_minus_means = tf.map_fn(lambda x: z - x, means)

    def internal(x):
        x = tf.reshape(x, (1,-1))
        return tf.matmul(tf.transpose(x), x)

    matrixes = tf.map_fn(lambda x: tf.map_fn(internal, x), z_minus_means)
    
    m_r = tf.reshape(matrixes, (12,4))
    m_r2 = tf.reshape(matrixes, (12,4)) * tf.reshape(tf.transpose(gamma), (12,1))
    m_r3 = tf.reduce_sum(tf.reshape(m_r2, (3,4,2,2)), [1]) 
    sigmas = tf.reshape(tf.transpose(tf.transpose(tf.reshape(m_r3, (3, 4))) / tf.reduce_sum(gamma, 0)), (3,2,2))
    
    means_minus_z = tf.map_fn(lambda x: means - x, z)
    
    def internal_e_1(z):
        #return (-0.5 * tf.map_fn(lambda x: tf.matmul(tf.matmul(tf.reshape(x, (1, -1)), z[1]), tf.reshape(x, (-1,1))), z[0]), 0.)
        #return tf.map_fn(lambda x,y: (tf.matmul(tf.reshape(x, (1, -1)), y), 0.), (z, sigmas), dtype=(tf.float32, tf.float32))[0]
        return tf.exp( -0.5 * 
            tf.map_fn(lambda x: tf.matmul(tf.matmul(tf.reshape(x, (1, -1)), tf.linalg.inv(z[1])),  tf.reshape(x, (-1, 1))),
                      z[0])) / tf.sqrt(tf.abs(tf.linalg.det(z[1])))

    #en_1 = tf.map_fn(lambda x: tf.transpose(x, (1,0,2)),means_minus_z)#, dtype=(tf.float32, tf.float32))
    en_1 = tf.transpose(means_minus_z, (1,0,2))

    en_2 = tf.map_fn(internal_e_1, (en_1, sigmas), dtype=(tf.float32))

    en = tf.reduce_mean(-tf.log(tf.reduce_sum(tf.transpose(tf.reshape(en_2, (3, 4))) * weights, 1)))
    
    return weights, means, sigmas, en

In [211]:
w, m, s, e = est_gmm(gamma, z)

In [10]:
weights = tf.reduce_mean(gamma, reduction_indices=[0])
means = tf.transpose(tf.matmul(tf.transpose(z), gamma) / tf.transpose(tf.reduce_sum(gamma, reduction_indices=[0])))

In [26]:
z_minus_means = tf.map_fn(lambda x: z - x, means)

def internal(x):
    x = tf.reshape(x, (1,-1))
    return tf.matmul(tf.transpose(x), x)

matrixes = tf.map_fn(lambda x: tf.map_fn(internal, x), z_minus_means)

In [84]:
m_r = tf.reshape(matrixes, (12,4))
m_r2 = tf.reshape(matrixes, (12,4)) * tf.reshape(tf.transpose(gamma), (12,1))
m_r3 = tf.reduce_sum(tf.reshape(m_r2, (3,4,2,2)), [1]) 
sigmas = tf.reshape(tf.transpose(tf.transpose(tf.reshape(m_r3, (3, 4))) / tf.reduce_sum(gamma, 0)), (3,2,2))

In [ ]:
z_minus_means_squared = tf.map_fn(lambda x: tf.reduce_sum(x * x), z_minus_means)
energy = tf.reduce_mean(-tf.log(tf.reduce_sum(tf.exp(-0.5 * tf.transpose(
    tf.reshape(z_minus_means_squared, gamma_arr.T.shape)) / sigma_flat) * weights  / tf.sqrt(6.28  * sigma_flat), 1)))

In [124]:
means_minus_z = tf.map_fn(lambda x: means - x, z)

In [212]:
def internal_e_1(z):
    #return (-0.5 * tf.map_fn(lambda x: tf.matmul(tf.matmul(tf.reshape(x, (1, -1)), z[1]), tf.reshape(x, (-1,1))), z[0]), 0.)
    #return tf.map_fn(lambda x,y: (tf.matmul(tf.reshape(x, (1, -1)), y), 0.), (z, sigmas), dtype=(tf.float32, tf.float32))[0]
    return tf.exp( -0.5 * 
        tf.map_fn(lambda x: tf.matmul(tf.matmul(tf.reshape(x, (1, -1)), tf.linalg.inv(z[1])),  tf.reshape(x, (-1, 1))),
                  z[0])) / tf.sqrt(tf.abs(tf.linalg.det(z[1])))

#en_1 = tf.map_fn(lambda x: tf.transpose(x, (1,0,2)),means_minus_z)#, dtype=(tf.float32, tf.float32))
en_1 = tf.transpose(means_minus_z, (1,0,2))

en_2 = tf.map_fn(internal_e_1, (en_1, sigmas), dtype=(tf.float32))

en = tf.reduce_mean(-tf.log(tf.reduce_sum(tf.transpose(tf.reshape(en_2, (3, 4))) * weights, 1)))

In [213]:
sess2 = tf.Session()
sess2.run(tf.global_variables_initializer())

sess2.run([sigmas, s, en, e], {gamma : gamma_arr, z : z_arr})

[array([[[ 2.07638884,  0.75694436],
         [ 0.75694436,  0.40972221]],
 
        [[ 1.05000007,  0.55000001],
         [ 0.55000001,  0.41      ]],
 
        [[ 1.35802472,  0.71604943],
         [ 0.71604943,  0.76543212]]], dtype=float32),
 array([[[ 2.07638884,  0.75694436],
         [ 0.75694436,  0.40972221]],
 
        [[ 1.05000007,  0.55000001],
         [ 0.55000001,  0.41      ]],
 
        [[ 1.35802472,  0.71604943],
         [ 0.71604943,  0.76543212]]], dtype=float32),
 0.41150391,
 0.41150391]

In [173]:
gamma_arr

array([[ 0.5,  0.1,  0.4],
       [ 0.3,  0.4,  0.3],
       [ 0.3,  0.4,  0.3],
       [ 0.1,  0.1,  0.8]])

In [133]:
z_minus_means = tf.reshape(tf.map_fn(lambda x: z - x, means), [-1, 2])

z_minus_means_squared = tf.map_fn(lambda x: tf.reduce_sum(x * x), z_minus_means)

sigma_flat = tf.reduce_sum(tf.transpose(tf.reshape(
        z_minus_means_squared * tf.reshape(tf.transpose(gamma), (1, -1)), gamma_arr.T.shape)), 0) / tf.reduce_sum(gamma, 0)

energy = tf.reduce_mean(-tf.log(tf.reduce_sum(tf.exp(-0.5 * tf.transpose(
    tf.reshape(z_minus_means_squared, gamma_arr.T.shape)) / sigma_flat) * weights  / tf.sqrt(6.28  * sigma_flat), 1)))



In [ ]:
i = tf.constant(0)
c = lambda i: tf.less(i, 10)
def b(i):
    
    return tf.add(i, 1)
r = tf.while_loop(c, b, [i])

In [23]:
def est_gmm(gamma, z):
    weights = gamma.mean(0)
    means = (T.dot( z.T, gamma) / gamma.sum(0)).T
    
    sigma_flat = T.vector()#(K)
    for j in range(K):
        sigma_j = 0
        for i in range(N):
            print 
            sigma_j += gamma[i][j] * T.dot(z[i] - means[j], (z[i]- means[j]).T)
        sigma_j /= gamma.sum(0)[j]
        #print(sigma_j.eval())
        
        sigma_flat[j] = sigma_j
    
    total_energy = 0
    for i in range(N):
        energy = 0
        for j in range(K):
            energy += weights[j] *np.exp(- 0.5 * np.dot((z[i] - means[j]), (z[i] - means[j]).T) / sigma_flat[j])
        energy /= np.sqrt(6.28 * sigma_flat[j])
        energy = - np.log(energy)
        total_energy += energy
    
    return weights, means, sigma_flat, total_energy / z.shape[0], np.abs(sigma_flat).sum()

In [24]:
est_gmm(gamma_arr, z_arr)

NameError: name 'T' is not defined