In [1]:
import crispr_assembler as ca
import pandas as pd
import numpy as np

In [102]:
clostr = pd.read_excel("./CDiParrays (copy).xlsx", sheet_name=None, index_col=None, header = None)#, header = None, index_col=None)

In [103]:
clostr.keys()

odict_keys(['77', '79', '210', '211', '221', '648'])

In [104]:
s = clostr['77'].values[:,0]

In [105]:
mask = pd.notna(clostr['77'][0]).values

In [106]:
[x for x in clostr['77'].values[mask][0][1:] if type(x) == str]

['TAACCTTTTTATTGTTGTTGTTATTCTTATTGTTATTC',
 'GTTGTAAGAAGTATCATTCTATTTTTTAATCTTTCT',
 'AGTACATATAATGAGTCTTTAACATCAGTTATGAAAG',
 'GATTGTACTTTAGCGTCTGCACTAGCTTTGTCTATC',
 'TATTTTACAGATGAACAATTACAGTTACTTCTTGAAT',
 'AATGGAAGCAAGATAATTTTTAAAGGTATGGATAATT']

In [126]:
def update(answer, source , prefix):
    mask = pd.notna(source[0]).values
    for i in range(mask.sum()):
        
        array = [x for x in source.values[mask][i][1:] if type(x) == str]
        key = source.values[mask][i][0]

        if len(array) > 0:
            answer[prefix + str(key)] = array    

In [127]:
clostr_dict = {}
# update(new_ecoli_dict, new_ecoli['Ecoli кассета 1'], 'first_')
# update(new_ecoli_dict, new_ecoli['Ecoli кассета 2'], 'second_')

In [152]:
for key, value in clostr.items():
    print(key)
    d = {}
    update(d, clostr[key], key+'_')
    d_str = {}
    for k,v in d.items():
        d_str[k] = '\t'.join(v)
    save_dict(d_str, str(key) + '_answ')

77
79
210
211
221
648


In [150]:
d

{'77_4': ['TAACCTTTTTATTGTTGTTGTTATTCTTATTGTTATTC',
  'GTTGTAAGAAGTATCATTCTATTTTTTAATCTTTCT',
  'AGTACATATAATGAGTCTTTAACATCAGTTATGAAAG',
  'GATTGTACTTTAGCGTCTGCACTAGCTTTGTCTATC',
  'TATTTTACAGATGAACAATTACAGTTACTTCTTGAAT',
  'AATGGAAGCAAGATAATTTTTAAAGGTATGGATAATT'],
 '77_9': ['CAAAGAAGCTCCACCCCATCTGTTTTTTATTATAGC',
  'TGTTTTCCATGAACATTTCGAGCTGACTTTTATTGT',
  'AACTTCTTGTTTTTTCTTTAAAACATGTACTTGGTC',
  'AAATCAATGCCAACTATAGGAACGTCGGGATTAATTG',
  'GGAGTATAAGGTAAATCGTAAGCAACTCCAGAAAGAG',
  'GAATTACAATATTATCTCCAGCATCAAGACTAGGAT',
  'CTGATAGAAAAAGAAGATTATTTGAAAGTTGAGACTA',
  'AAAGATTGCAATAGATTTCCTGTTAAAATAGGTACAG',
  'GAAATAATAAATAGCATTGTCGAATGGTTTGCAAGCC',
  'TATAGCTAATTATTAGATTCAATTTTAATTTCGTTAA',
  'ATTGCAACACTTCATCAGTTGATAAATATAGTATATT',
  'TTATACATATTTGTAGCTCCTTGCTGAACTGTTGCA',
  'TGGTTAAATCTCCAACAGAACATTTATCTAAATTACAA',
  'CTTGTTAATGCAAATAAACAACATAGCACTATTAATA',
  'AGGGTTTCTGATAAAATCTTCAAACATGTAAAATATGT',
  'CTTATACTTAGTTAGAACTATATATCGACACAAATAT',
  'TGCAATTTTTATTCGTTGTCCAATCTCTTTGAAATTT'

In [132]:
d630 = ca.read_arrays_with_tags("../../data/answers/Clo_009089.txt", 0)

In [133]:
d20291 = ca.read_arrays_with_tags("../../data/answers/Clo_013316.txt", 0)

In [147]:
clostr_answer = {}

for d in [clostr_dict, d630, d20291]:
    for k, v in d.items():
        if len(v) > 0:
            clostr_answer[k] = '\t'.join(v)

In [142]:
ca.dict_to_csv(clostr_answer, './clostr_answer')

In [143]:
clostr_answer_short = {}

for d in [d630, d20291]:
    for k, v in d.items():
        if len(v) > 0:
            clostr_answer_short[k] = '\t'.join(v)

In [144]:
ca.dict_to_csv(clostr_answer_short, './clostr_answer_short')

In [148]:
save_dict(clostr_answer, './clostr_answer')

In [145]:
def save_dict(d, fname):
    with open(fname, 'w') as f:

        for k,v in d.items():
            f.write(k)
            f.write("\n")
            f.write(v)
            f.write("\n")

    

In [74]:
sensivity_set = [2,3,5,7,8,11,14,15,21,22]

In [80]:
keys  = np.array([int(x.split('_')[1]) for x in new_ecoli_dict.keys()])

for x in sensivity_set:
    if x in keys:
        print(np.where(keys == x))
    else: 
        print(x)
    

(array([ 2, 23]),)
(array([ 7, 32]),)
(array([ 8, 27]),)
(array([10, 33]),)
(array([11, 34]),)
(array([ 1, 35]),)
(array([12, 36]),)
(array([13, 37]),)
(array([18, 29]),)
(array([16, 40]),)


In [85]:
keys

array([ 1, 11,  2, 24, 61, 62, 68,  3,  5, 50,  7,  8, 14, 15, 19, 20, 22,
       31, 21, 23, 27, 65,  1,  2, 61, 62, 68,  5, 50, 21, 65, 70,  3,  7,
        8, 11, 14, 15, 19, 20, 22, 23, 24, 27, 31])

In [89]:
def filter_dict(data_dict, list_tags):
    filtered_dict = {}
    
    for k,v in data_dict.items():
        if int(k.split("_")[1]) in list_tags:
            filtered_dict[k] = v
        
    return filtered_dict

In [97]:
save_dict(filter_dict(new_ecoli_dict, sensivity_set), "../../article/data/answers/sensivity")