In [1]:
import crispr_assembler as ca
import pandas as pd
import numpy as np

In [5]:
new_ecoli = pd.read_excel("../../New EColi CRISPR arrays(2).xlsx", sheet_name=None, header = None, index_col=None)

In [6]:
new_ecoli.keys()

odict_keys(['Ecoli кассета 1', 'Ecoli кассета 2'])

In [7]:
new_ecoli_1 = new_ecoli['Ecoli кассета 1']

In [8]:
def update(answer, source , prefix):
    for i, row in source.iterrows():
        names = row[0]
        if type(names) == str:
            #names = [int(x) for x in names.split(',')]
            names = [names]
        else:
            names = [names]

        for name in names:  
            name_str = str(name)
            for single_name in name_str.split(','):
                mask = pd.notna(row[1:]).values
                array = "\t".join(row[1:].values[mask])

                answer[prefix + single_name] = array

In [9]:
new_ecoli_dict = {}
update(new_ecoli_dict, new_ecoli['Ecoli кассета 1'], 'first_')
update(new_ecoli_dict, new_ecoli['Ecoli кассета 2'], 'second_')

In [10]:
new_ecoli_dict

{'first_1': 'AAAACCAAACTTCTCCATAAATTCCATAGCCG\tGAGTCTATCAGCGACACTACCGGCAATAGCGA\tCTATAGCGCCACGTTCCGAGCGCTGCGAGCTG\tCTAATGAGTCAGTTTGAACAGATCCCCGACAA\tGGCTTTAAAATTGTGTTCCCGTCTGGCGCTGG\tGCATCCATGCCGACGCCTTTACGTGTGCGGGG\tGCGCGAATTTGTGCGCATGGGGCGCATTTTTGG',
 'first_11': 'AAAACCAAACTTCTCCATAAATTCCATAGCCG\tGAGTCTATCAGCGACACTACCGGCAATAGCGA\tCTATAGCGCCACGTTCCGAGCGCTGCGAGCTG\tCTAATGAGTCAGTTTGAACAGATCCCCGACAA\tGGCTTTAAAATTGTGTTCCCGTCTGGCGCTGG\tGCATCCATGCCGACGCCTTTACGTGTGCGGGG\tGCGCGAATTTGTGCGCATGGGGCGCATTTTTGG',
 'first_2': 'TCTAAGTGATATCCATCATCGCATCCAGTGCGCC\tTCTTACTGCTTGGTATGCGGAATCACACCCTGAA\tACTGAAGCATCAAACATTTGGTGGACCAAACGGA\tACTGTACGCGGCGAGTTTTAGCGACAGGTCATCC\tACGGATCTGCCAGCGCCTCTGCGGGGCGGTAAAC',
 'first_24': 'TCTAAGTGATATCCATCATCGCATCCAGTGCGCC\tTCTTACTGCTTGGTATGCGGAATCACACCCTGAA\tACTGAAGCATCAAACATTTGGTGGACCAAACGGA\tACTGTACGCGGCGAGTTTTAGCGACAGGTCATCC\tACGGATCTGCCAGCGCCTCTGCGGGGCGGTAAAC',
 'first_61': 'TCTAAGTGATATCCATCATCGCATCCAGTGCGCC\tTCTTACTGCTTGGTATGCGGAATCACACCCTGAA\tACTGAAGCATCAAACATT

In [12]:
new_ecoli = pd.read_excel("../../article/data/answers/Cheked spacers EColi.xlsx", sheet_name=None, header = None, index_col=None)
update(new_ecoli_dict, new_ecoli['CRISPR1'], 'first_')
update(new_ecoli_dict, new_ecoli['CRISPR2'], 'second_')

In [13]:
def save_dict(d, fname):
    with open(fname, 'w') as f:

        for k,v in d.items():
            f.write(k)
            f.write("\n")
            f.write(v)
            f.write("\n")

    

In [14]:
save_dict(new_ecoli_dict, "../../article/data/answers/all_refresh")

In [35]:
sensivity_set = [2,3,5,7,8,11,14,15,21,22]

In [36]:
3,5,14,15,8,21,

(3, 5, 14, 15, 8, 21)

In [37]:
keys  = np.array([int(x.split('_')[1]) for x in new_ecoli_dict.keys()])

for x in sensivity_set:
    if x in keys:
        print(np.where(keys == x))
    else: 
        print(x)
    

(array([ 2, 28]),)
(array([ 7, 37]),)
(array([ 8, 32]),)
(array([10, 38]),)
(array([11, 39]),)
(array([ 1, 40]),)
(array([12, 41]),)
(array([13, 42]),)
(array([18, 34]),)
(array([16, 45]),)


In [45]:
with open("../../../CRISPR_research/new_ecoli.txt", 'w') as f:
    for key in new_ecoli_dict.keys():
        f.write(new_ecoli_dict[key] +  "\n")
    

In [48]:
keys = [x.split("_")[1] for x in new_ecoli_dict.keys()]

In [53]:
sorted([int(x) for x in list(set(keys))])

[1,
 2,
 3,
 5,
 7,
 8,
 9,
 11,
 12,
 14,
 15,
 19,
 20,
 21,
 22,
 23,
 24,
 27,
 31,
 50,
 61,
 62,
 65,
 66,
 67,
 68,
 70]

In [5]:
def filter_dict(data_dict, list_tags):
    filtered_dict = {}
    
    for k,v in data_dict.items():
        if int(k.split("_")[1]) in list_tags:
            filtered_dict[k] = v
        
    return filtered_dict

In [4]:
save_dict(filter_dict(new_ecoli_dict, sensivity_set), "../../article/data/answers/sensivity")

NameError: name 'save_dict' is not defined

In [42]:
save_dict(filter_dict(new_ecoli_dict, equal_set), "../../article/data/answers/equal")

In [55]:
save_dict(filter_dict(new_ecoli_dict, sorted([int(x) for x in list(set(keys))])), "../../article/data/answers/all")

## Check old answers

In [50]:
second_old = {}

In [19]:
old_ecoli = pd.read_excel("/home/anton/Downloads/crispr (1).xlsx", sheet_name=None, index_col=None)

In [20]:
old_ecoli.keys()

odict_keys(['презент', 'кассета 1 ECOR', 'схема1', 'ECOR', 'кассета1', 'Spasers', 'кассета 2 ', 'кас 2 moj', 'Lyuba', 'кассета 2 ECOR', 'cas2 time'])

In [30]:
name = 'кассета 2 '
mask = pd.notna(old_ecoli[name][0]).values

In [49]:
data = np.hstack((old_ecoli[name].values[mask, 1:2],old_ecoli[name].values[mask, 4:]))

In [53]:
for row in data:
    second_old[row[0]] = [x for x in row[1:][pd.notna(row[1:])] if len(x) > 1]

In [64]:
first_old = {}

In [60]:
name = 'кассета1'
mask = pd.notna(old_ecoli[name]["№ изолятов"]).values

In [61]:
data = np.hstack((old_ecoli[name].values[mask, 1:2],old_ecoli[name].values[mask, 4:]))

In [69]:
for row in data:
    first_old[row[0]] = [x for x in row[1:][pd.notna(row[1:])] if len(x) > 12]

In [71]:
import pickle

In [72]:
pickle.dump(first_old, open("./first_old_answers", 'wb'))
pickle.dump(second_old, open("./second_old_answers", 'wb'))